import Head from 'next/head'
import { useState, useEffect } from 'react'

interface Square {
  bomb: boolean;
  checked: boolean;
}

const WIDTH = 20;
const HEIGHT = 10;
const BOMB_WEIGHT = 0.3;

export default function Home() {
  const [board, setBoard] = useState<Square[][]>([]);

  useEffect(() => {
    let temp: Square[][] = []
    for (let y = 0; y < HEIGHT; y++) {
      let row: Square[] = []
      for (let x = 0; x < WIDTH; x++) {
        row.push({
          bomb: Math.random() < BOMB_WEIGHT,
          checked: false
        });
      }
      temp.push(row)
    }

    setBoard(temp)
  }, [])

  return (
    <div>
      <Head>
        <title>Minesweeper</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="flex flex-col">
        {board.map((item) => (
          <Row row={item} />
        ))}
      </main>
    </div>
  )
}

function Row(props: { row: Square[] }) {
  return (
    <div className="flex flex-row">
      {props.row.map((item) => (
        <Square data={item} />
      ))}
    </div>
  );
}

function Square(props: { data: Square }) {
  return (
    <div className="w-8 h-8 m-1 bg-blue-500 hover:bg-blue-400 rounded text-center grid place-content-center text-white cursor-pointer">{props.data.bomb ? "1" : "0"}</div>
  )
}
